//------user-----
export const USLISTPRODUCT = 'USLISTPRODUCT';
export const USDETAILSPRODUCT = 'USDETAILSPRODUCT';
export const ADDTOCART = 'ADDTOCART';
export const DELTOCART = 'DELTOCART';
export const DANGKYUSER = 'DANGKYUSER';
export const GETUSER = 'GETUSER';
export const ADDTOBILLAPI = 'ADDTOBILLAPI';
export const GETPROFILE = 'GETPROFILE';
export const GETHISTORYCART = 'GETHISTORYCART';
export const SEARCHPRODUCTS = 'SEARCHPRODUCTS';
export const GETCATEGORY = 'GETCATEGORY';
export const CHECKLOGIN = 'CHECKLOGIN';
//------admin-----
export const GETADMINLOGIN = 'GETADMINLOGIN';

export const GETLOAISP = 'GETLOAISP';
export const ADDLOAISP = 'ADDLOAISP';
export const DELETELOAISP = 'DELETELOAISP';
export const EDITLOAISP = 'EDITLOAISP';
export const UPDATELOAISP = 'UPDATELOAISP';
export const SEARCHLOAISP = 'SEARCHLOAISP';

export const GETSANPHAM = 'GETSANPHAM';
export const GETSHOWCATE = 'GETSHOWCATE';
export const ADDSANPHAM = 'ADDSANPHAM';
export const DELSANPHAM = 'DELSANPHAM';
export const EDITSANPHAM = 'EDITSANPHAM';
export const UPDATESANPHAM = 'UPDATESANPHAM';
export const SEARCHSANPHAM = 'SEARCHSANPHAM';


export const GETACCUSER = 'GETACCUSER';
export const SEARCHACCUSER = 'SEARCHACCUSER';

export const GETBILLAD = 'GETBILLAD';
export const EDITBILLAD = 'EDITBILLAD';
export const UPDATEBILLAD = 'UPDATEBILLAD';
export const SEARCHBILLAD = 'SEARCHBILLAD';